package com.darkdeymon.ceub_potosi.staticDataClases;

import com.darkdeymon.ceub_potosi.clases.Turismo;

import java.util.ArrayList;

public class TurismoData {
    private static ArrayList<Turismo> turismo = new ArrayList<Turismo>();
    private static boolean llenadortu = true;

    public static ArrayList<Turismo> getTurismoData(){
        if(llenadortu){

            turismo.add(new Turismo(
                "Casa Nacional de Moneda",
                "La Casa Nacional de Moneda de Bolivia, conocida también como la Real Casa de Moneda o simplemente como la Casa Nacional de Moneda, se encuentra en la ciudad de Potosí, fundada en 1572 por el virrey Francisco de Toledo.\n" +
                        "En los años cuarenta del siglo XX, el Gobierno de Bolivia mediante un Decreto Supremo del 5 de octubre de 1940, entregaba la antigua Real Casa de Moneda de Potosí a la Sociedad Geográfica y de Historia \"Potosí\" para su administración y organización de un museo y archivo histórico. En la actualidad este repositorío cultural se ha convertido en un centro museológico y documental muy conocido a nivel nacional e internacional.\n",
                "Hoyos",
                "https://www.eldeber.com.bo/__export/1508356605303/sites/eldeber/img/2017/10/18/casa_de_la_moneda_0.jpg_1775534641.jpg",
                -19.588905f,
                -65.754258f
            ));
            turismo.add(new Turismo("IGLESIA DE SAN BERNARDO","corresponde al siglo XVIII, fue reconstruida totalmente por el arquitecto, Bernardo Rojas, en 1727, concluyéndola cuatro años después. Edificada en piedra sin labrar, toda la obra es de cal y canto.Poco después que se fundó la República de Bolivia, se dispuso la construcción de cementerios únicos en cada ciudad, para que sustituyeran a los cementerios parroquiales. Para Potosí, se escogió el atrio de San Bernardo.","Avenida Camacho","https://lh3.googleusercontent.com/V7yfzrwlhNEZUozSzOA1Bb8mwhPK_4N0IxGfWT-doCuEoPL61zacnuTzjAPzSYcliLJKrkl4Rij4wOILvZz80yhy26X9g11Ec6zBEEY-0DfYymGIZjyTFh0h93NPaf23EcJHrfgcyQ=w2400",-19.586075f,-65.75689f));
            turismo.add(new Turismo("IGLESIA DE SAN AGUSTIN","La iglesia, capilla y convento de Nuestra Señora de Aránzazu, patrona de los vascongados data del siglo XVII. Lo único que queda es la portada de estilo renacentista.","Calle Bolivar esq. Quijarro","https://lh3.googleusercontent.com/ojmKfkXOtU0bICPg3gGZelFAyemPf5vceOFeR8lIRpYrO9FIdIsR7c54mma8eAA9Ogmn9lFs9TAXSpRaFG-S7VvJxBY9vK4Hz0SdzAqSuGcu_Se7u76-r5aB6u-LoP0BU8TRYoXF0A=w2400",-19587425f,-65.75364f));
            turismo.add(new Turismo("IGLESIA DE SAN LORENZO DE CARANGAS","egún el historiador Arzanz Orzúa y Vela, una de las primeras iglesias edificadas en Potosí, fue La Anunciación (San Lorenzo), destinada con exclusividad a los españoles. Se inició la construcción en 1548.A la llegada deL Virrey Toledo, pasó a ser parroquia de indios cambiando el nombre por el de San Lorenzo de Carangas.","Calle Heroes del Chaco","https://lh3.googleusercontent.com/CBBNdcf3PgHUIi_nN35qsCJ-_A5SZ4I7ByHB2WQHxLdyWHWVDqrne0JiAksp_y5_8LqQv-SUkl9d7ls6FJNkBXtchQUgjDXSgNe6yoUHA5-wC9c9Zx67BJ5NXOjxSHqHcNimJKLkUw=w2400",-19.586848f,-65.754783f));
            turismo.add(new Turismo("IGLESIA DE SAN PEDRO","Esta fue una parroquia de indios Pacajes de Umasuyo que se quemó en 1655 por lo que fue reformada en el año de 1725. Conserva su tipología original.En su interior alberga actualmente el púlpito y un altar del templo de Salinas de Yocalla que son una de las mayores joyas del barroco mestizo. La portada en su reforma fue redecorada en su estilo mestizo habiéndose recobrado en la portada de pies la policromía original.","Calle Perez de Olguin","https://lh3.googleusercontent.com/qr4zOjWn8qXil2ZklPeUOKfek65PBe_qqxbkHba_sg74uvU-_qPP2TWyojYnYbeaJvILKfyoJzIYlL9d4cF2fvDMvfnQzHzIVDtwB3aLs8C_-w_XnMdMMZbDg6edYHb27xSSXXyk9Q=w2400",-19.594412f,-65.752270f));
            turismo.add(new Turismo("IGLESIA Y CONVENTO SANTA TERESA","El museo está instalado en los claustros y la segunda del convento, que mantiene su arquitectura virreinal, y muestra una de las mejores colecciones pictóricas en el país. Tenemos que agregar modificar piezas, tallas de madera, materiales ricos, muebles, libros, reliquias, objetos de plata y diversos objetos de la cemturis XVII y XVIII.Al final de su visita, usted podrá comprar quesitos que son dulces de mazapán elaborados por las monjas, como hace tres siglos.","Calle Cochabamba esquina Ayacucho","https://lh3.googleusercontent.com/RmUK2JDia7ZBUX77P7nrCFPyYdhAQjpOJpfzRV9qcjdmdvNGUrhH-3f7fFNs_J0PZGeQPYsRG_zXiNaB4HYx_sudr8F7p647StS5Tt-4MGIvb9Ks-3878UL-hhpDcAdA0nUESW1-DA=w2400",-19.588989f,-65.757008f));
            turismo.add(new Turismo("IGLESIA DE JERUSALEN","No fue construida como iglesia conventual ni como parroquia de indios, sino, simplemente como un santuario para la devoción de la virgen de la Candelaria, aparecida en 1623 y que aún se conserva hasta nuestros días.La construcción definitiva data de 1702. El templo fue inaugurado en 1708 con el nombre de Nuestra Señora de Jerusalén que dependía de la Iglesia de San Lorenzo.","Avenida Universitaria","https://lh3.googleusercontent.com/zPRhkUgx00J6Jdn9nQtyt3KkO59glaBJ0TzX_MRItPxqLKZa9Ktif3yrGVqHreKnv38-yBxJFzyd6ejcppTCmo1xMb1Tc7XD39IklGC8c-sNchMthRhkFZH3HV9CgzCin2HvDqWlIg=w2400",-19.584939f,-65.757086f));
            turismo.add(new Turismo("IGLESIA DE LA CONCEPCION","Ya para el año 1585, se hallaba establecida la parroquia de indios de Nuestra señora de la Concepción, atendida por los frailes dominicos a principios del siglo XVII.La portada principal fue remodelada en el siglo XVII, actualmente se mantienen la portada de piedra y la nueva torre espadaña.En su interior funciona el Museo de Indios Mitayos.","Calle Hernandez","https://lh3.googleusercontent.com/75Xz9rLYR_8leeLozXEqBgO7F-PWXtsEplHGjwNuLUO2b__Qs66wE5ttWOIyrrrD7maBwr88jBfx8flhDCjevQdjb45tMS-ezJjyXJzeoyeAipW21ewfkphe2dh8p5krrCnKTJs9yA=w2400",-19.592641f,-65.746874f));
            turismo.add(new Turismo("IGLESIA DE SAN CRISTOBAL","Es una de las más conservadas en su tipología de Potosí y de la Audiencia de Charcas.Mantiene las características renacentistas.","Calle Pacheco esquina Ramos","https://lh3.googleusercontent.com/hZEFAoY8Q23_5er8ozBUVLp4R-SVsEijNVgUxGMgT1b6KXYW_mLcJm9b5_nsIm6pRRBkIHBjbbcPPpIdUqlFyXuaploBBhVgJ8SuJ5qn7JF4bN34pmkg8Bfn_Fv9zg2NpaifwJWtLA=w2400",-19.595821f,-65.745754f));
            turismo.add(new Turismo("IGLESIA DE SAN JUAN","Esta parroquia fue construida para los mitayos de Lupacas, pertenece al siglo XVI. Su cubierta es rústica de estructura de par y nudillo. Posee dos portadas sobrias, la de la cabecera con mayor ornamentación y pilastras dóricas.","Calle Hernandez esquina Chuquisaca","https://lh3.googleusercontent.com/IBY4EuT8sGGpku6qz4Uw-d0jUQXNGzAUFC316pfjH-cJxPd6UMOD4UO0TBmSsD1L1Nmnjc2mbSaFXWwV4S3bSifjEcYigPmakPV5CREESSMO0-JamhG6Q8lCHwDyxk9o_INtxY2aRw=w2400",-19.590214f,-65.746236f));
            turismo.add(new Turismo("IGLESIA DE SAN SEBASTIAN","Fue edificada en 1581. Su planta es de cruz latina. En 1725 se estrenó la cúpula de media naranja sobre el crucero tal como aparece hoy en día. Interiormente conserva el coro alto, el retablo mayor y el púlpito tallado en madera.","","https://lh3.googleusercontent.com/-AEOeDOfi6cgutbm0z5ssj6_C7lnCF0QlfJomTCCT0i0axusORAZEZi3pCKBi3ObzfVAEtLeAY2juIsX5u4TPdi_hrPd8y3OtG1L7xjdk08Oks1Ot5IfFYZvBm1FcvL5uA-Qefc3yw=w2400",-19.592747f,-65.749856f));
            turismo.add(new Turismo("CAPILLA CAJA DE AGUA","Capila que pertenece a la Caja de Agua ","Calle Chuquisaca y Plaza Centeno","https://lh3.googleusercontent.com/qpfCYQIHa6brCo44_5J3A3cM1UiH9JGazvaaqXX4cT0fRdJZMqWbSi0YBKUuYnKdoCS1o97yJ8dVpwrBHVGlGgkcUKznjYCS09Q9jI6L7zeRDgSf2mzsbksyYvA1w17JH0B7pQTH5A=w2400",-19.590060f,-65.745642f));
            turismo.add(new Turismo("CAPILLA HERNANDEZ","Ubicada cerca de la Iglesia de Nuestra Señora de Concepcion","Calle Herrnandez esquina Betanzos","https://lh3.googleusercontent.com/59joHXXmPzA0OHF5cb1KArCcEAGM5Gq8C6P3KU9AvscO9AKjAMziYiO2aBTZd4TGzCpMe5ypGqd2NxShOOkegVXjZsTy6DFD6XcOOd9w67zcsB14BZoUry3QLL2WqvsjRC-Br4mVGg=w2400",-19.593300f,-65.746769f));
            turismo.add(new Turismo("IGLESIA DE SAN BENITO","Originalmente estaba destinada a los indios mitayos Kollas de Urcosuyo y Cochabamba.En el siglo XVIII por influencia del estilo barroco se cambió la cubierta de par y nudillo por cúpulas de media naranja sobre la estructura antigua y se cambió la planta de una sola nave por una de cruz latina. En 1916 se cayó la torre de dos cuerpos y fue remplazada por una  torre espadaña.","Zona San Benito","https://lh3.googleusercontent.com/rv_hRKL4NHUjSPqY5RFhMsSIsz_ijhyHgVRireCU9Zi9IVUs4IiU_Nj7B--xdZ0oHeyod7bzSyg9RimHT9w7CP7zJ5rw2yZ4plA4-QA9zXbTHWoyLg__2ZmGi7fjXqxRh7NzNam4vQ=w2400",-19.591559f,-65.760264f));
            turismo.add(new Turismo("IGLESIA DE SAN MARTIN","Esta iglesia fue construida por los indígenas que vinieron de diversos lugares para llevar a cabo su servicio obligatorio cumplimiento en las minas. Perteneció a la Orden Mercederian.La primera construcción data de 1592. Su estructura original presenta una sola nave con ladrillos de barro espera, una copia de una copia de la torre, el atrio y las capillas que pasa campana.","Calle Hoyos ","https://lh3.googleusercontent.com/iwJbOAPyK4zRvBFrn7789L3uCTbF-gTZ8whFnf8KbG-637yY6qQzwYJVXr2YceiBBAK6L2QI0UhQtkjiEBU3IQPqViJiWldyVsGE1BSl209eb2taaCM68JaP6JmXIdaYOgjlGAm5jA=w2400",-19.588448f,-65.747707f));
            turismo.add(new Turismo("TEATRO MODESTO OMISTE","La religión Bethlemitas llegó a Potosí en 1700 y desde su objetivo era cuidar de los hospitales de Real de la Vera Cruz que hoy está en muy mal estado, fue entregado a ellos. Así, la Orden de Nuestro Señor de Bethlem de Potosí fue fundada. El edificio cayó en 1725 debido a las fuertes lluvias caídas. El trabajo de la nueva iglesia fue dada a Bernardo Rojas Luna y Saldaña y se concluyó en 1753.","Calle Hoyos No. 90","https://lh3.googleusercontent.com/bFy8YPFYUnJeXXJLtcXZOrI2uA3hLha8Pf-pdNNswAvlzkP2MwDbuTzMMQdOi6EhMxbZXKitT76fPwriY858CJmIpv1kJ2d0XKnAeQgZRTJRRRPzR7utCvSXGlllKB7GFKnM3C0L-A=w2400",-19.588689f,-65.752785f));
            turismo.add(new Turismo("CAJA DE AGUA","ue edificada en 1775, con ocho estanques para purificar el agua, precisamente para abastecer de agua en el trabajo de acuñación de moneda.Hoy funciona como el Acuario Municipal.","Calle Chuquisaca esq. Plaza Sucre","https://lh3.googleusercontent.com/pBnrW9To-5wPDh8rbiShv11GuTzkXK6A6BaXhqieLg7dM_ITlYaACp1ByNwkwNcjQ1refJq6Pria3YwBwuiK9Dnm2nZqQdPGTI4EyjL8kxBkXrKpVBCt4vDygNXun5MO3DgWDi0Yyw=w2400",-19.590079f,-65.745467f));
            turismo.add(new Turismo("ARCO DE COBIJA","Servía de límite del área española de la ciudad, su nombre se debe al puerto colonial de la Audiencia de Charcas “Magdalena de Cobija”.Desde este punto se tiene la mejor vista de la Torre de Santa Bárbara y de San Benito.","Calle Cobija y Mejillones.","https://lh3.googleusercontent.com/Dm_Qa3i2170aPx96xtgFaDzA0D-nZ-ZxPmFB9D_sXqWYxw-G0vXMJbF6xuHiWJ1ToZi_F6ZxwIljydrsdQ1Zobnt02AhEMFm10ke7STC1oIqjivknptQzpDJ55FszQwZIDLtAsEGhQ=w2400",-19.589810f,-65.756459f));
            turismo.add(new Turismo("HOSPITAL REAL BETLEMITA (COLEGIO PICHINCHA)","Fue en ese colonial edificio conventual donde quedó establecido el primer colegio de ciencias y artes de Potosí con el notable nombre de Pichincha (en conmemoración a la Batalla de Pichincha)","Calle Hoyos esquina Junin","https://lh3.googleusercontent.com/ZKLMClCy0rXtGe8NfDP5krRWnim_9wal0VnnxobmO-bOv4nGC9QzQt83gBaarT6MS9NRt0VhheNUItBahQgZ3Gr3kYU02WgBtJIexpCTxJKJ7M8XCo9s3j8WzjlyIrviedeR5JAeCw=w2400",-19.588746f,-65.753032f));
            turismo.add(new Turismo("ILGESIA SAN JUAN DE DIOS","Jurisdiccion: DIOCESIS DE POTOSÍ","Calle Chuquisaca.","https://lh3.googleusercontent.com/JbyRlK8h3kDXtOprfPUVd5X-BT-02h8rl6gp2u55iNIg3Obe-dXusg0UnIJ9mMpJNVoNFEt4HVNpyxA4CspLN8-9OS8xfKK0_lGP9m69Hbs1PfjPEBqrMC303-2tjgGrp1AFb0c_Rg=w2400",-19.590124f,-65.750965f));
            turismo.add(new Turismo("CASA DE LOS OFICIALES REALES","La construcción  pertenece al siglo XVIII, fue el segundo edificio más importante después de la Casa de Moneda. Éste, ha sido rehabilitado como el primer ejemplo de vivienda social en Bolivia, conservando la tipología original del inmueble.","Calle Bolivar esq. Oruro","https://lh3.googleusercontent.com/dIeG7zd1QavQGegIjblUc7gopoY6YwhwUeOty--6HzU5yN9J3IGnm2ATIVQcCF2bsmJfKtUVwQ8Qm9vfcH-yH95ctcJWK-p-n_kq3p_BXcf8eabsENdnI7PY3zUjVY88i_XR0JQajg=w2400",-19.587555f,-65.755532f));
            turismo.add(new Turismo("ARCO DE MEJILLONES","El Arco de Cobija y el Arco de Mejillones, quedan a unas pocas cuadras del Convento de Sta. Teresa, forman parte del Circuito histórico de San Benito, delimitaban la parte indígena y española de la ciudad, es el sector de Potosí colonial indígena, con calles coloniales muy estrechas, viviendas de la época","Calle Mejillones","https://lh3.googleusercontent.com/8bmlrGKycQEI95j8LZNo91hbqRFckP1g6Qx_yxeQYILWlCnKS_uwQ15drcxWm8wOk1KoBkp7fhT5T_H2kjxwQcNtzLlAOMduRX74iAtiE6EHlSyV-Z1LWaEMjM-I0TYANfbJQeNTag=w2400",-19.591367f,-65.757547f));
            turismo.add(new Turismo("REAL CASA DE LA MONEDA","La Casa de la Moneda nacional actualmente sirve como museo y archivo histórico. En el museo, uno puede apreciable las pinturas de Pérez de Holguín, Gamarra, Berrio y Cruz, entre otros. El recorrido ofrece visitas a las salas de la numismática, alterar piezas, mineralogía, etnología, artesanía, etc","Ayacucho S/N","https://lh3.googleusercontent.com/sVPpApUFBanQ41bMw8gOIln6btwWeLXX4iltVxzyWK_TUQUSxuScz-v8A5wCmgc6F3SDkLllKEN7Yx1YxOfu4kFLryUWZglZ45mLzFVFJK4CJM5Ks9SRueQAxvCipHaglJuXBzeEOw=w2400",-19.588530f,-65.754181f));
            turismo.add(new Turismo("TAMBO DE LA CRUZ","Edificación que posee un cuarto de manzano, cuya fachada mantiene su estructura original con muy pocas reformas, la misma que posee una portada sencilla de ladrillo y cal.","Calle Chuquisaca esquina Porco","https://lh3.googleusercontent.com/sVPpApUFBanQ41bMw8gOIln6btwWeLXX4iltVxzyWK_TUQUSxuScz-v8A5wCmgc6F3SDkLllKEN7Yx1YxOfu4kFLryUWZglZ45mLzFVFJK4CJM5Ks9SRueQAxvCipHaglJuXBzeEOw=w2400",-19.589944f,-65.749940f));
            turismo.add(new Turismo("IGLESIA DE SANTO DOMINGO","La orden de predicadores de Santo Domingo, fue la segunda en establecerse en la ciudad. El convento se remonta al año 1553 y el templo fue terminado en 1620; sus portadas son renacentistas siendo la lateral al templo el único ejemplo policromo de esa época que se conserva en Potosí y de los pocos en América.","Calle Cobija esquina Oruro","https://lh3.googleusercontent.com/l_t78wC-gudwS-rCym7YxdiuWZf-apCrNlWgyYQFWp4EkViF4nLxVABxW-IZLJK3A61jd5aAu9WmP5mYNiEMj4JdQtquGyaAnScTgYimCgP0-vDcMHD-TksGuyIJ4J1V4QpIkxB22Q=w2400",-19.589732f,-65.755428f));
            turismo.add(new Turismo("CATEDRAL DE POTOSI","La Iglesia primitiva importante se había iniciado 1564. El templo de una sola nave, se derrumbó en 1807. La actual catedral, que ocupa el mismo espacio que su predecesor, es obra del arquitecto Fray Manuel de Sanahuja, que comenzó en 1808. Fue inaugurado en 1836.","Plaza 10 de Noviembre","https://lh3.googleusercontent.com/XMDjNFVv8g85w-Qn-pQqONxADjY6gUhSYrH4w5t3hdPHNoX8qS9-vn50SYiK7etsOB8GVpE1ULMPaFWtkWiEIllXIsxx1jmWYaqitsKL06UoQfgo2NB5C-zxvtfge4o-fOhtMbEE7A=w2400",-19.588588f,-65.753414f));
            turismo.add(new Turismo("IGLESIA DE LA MERCED","Iglesia La Merced. Fundada en el siglo XVI en el departamento de Potosí, Bolivia. Posee una de las portadas más importantes de la arquitectura de la región. Es una de las Iglesias más ambiciosas entre las mercedarias de Charcas, una de las mayores en dimensión entre las que se hicieron en el siglo XVI.","Calle Hoyos","https://lh3.googleusercontent.com/XoGknRlza72JNQbK4elVl4WL3b_I6AE5FL30yvsOuPg4RXvhEEOID-PnZTVPRrRhFJx_0YGIrrz-sVLV6khslBvoCx5rkSSp9WCFXigsGbynT8trPt8cDt2A4nqrsk286oaDYdTrCg=w2400",-19.588714f,-65.751820f));
            turismo.add(new Turismo("TORRE DE SANTA BARBARA","Santa Bárbara fue la primera parroquia de indios que se construyó en Potosí  entre 1547 y 1552 de la cual sólo se conserva la torre, cuya estructura es de adobe con base cuadrada. Se halla dentro de la Unidad Educativa Cleto Loayza y su acceso es dificultoso.","Calle H. Basquez","https://lh3.googleusercontent.com/IBnnuSXUzkSS0fBE4YWSfsrBrKsLJsxOoAcqoD8oWN8MN-Vrkc8nDsKuxLLrtOHYilZnQ3Ce-Y3HRVdy0yBdNf07DdG7xsRC4pzE5slB6a76u6TlRIkGioqusyYscJn_dKyvU-60yQ=w2400",-19.591827f,-65.758465f));
            turismo.add(new Turismo("PLAZA 10 DE NOVIEMBRE","La plaza principal o plaza mayor de una ciudad, es sin duda alguna, el alma de su historia. Era denominada plaza del Regocijo durante la colonia, debido a que se realizaban allí múltiples festividades.Un paseo alrededor de ella,  permitirá encontrar  edificios que cumplieron una función muy importante durante la coloniaLos edificios que estaban en la Plaza Mayor fueron del lado sur, las Cajas Reales (hoy edificio del Gobierno Municipal), y la primera Casa de Moneda (hoy edificio de la Corte Superior del Distrito Judicial); en el lado norte, la Iglesia Mayor (hoy Catedral); en el lado oeste el Cabildo (hoy edificio de la Gobernación del Departamento); y    en lado este, edificios civiles como el primer Casino de Potosí, hoy Club Internacional.","Plaza 10 de Noviembre","https://lh3.googleusercontent.com/OLjsXUjzUVBJ_wbNMFQCFQfUHtBtTIY9e_V6tW5r2VLtqklzRzQmR2Sm83KIy49RBfUFAAAXcohPMdIHRo8CCH7h7Y7Ck6fRc6zTgWx0pfOCjEQjb58R5O6OkDLWZW0a9MtCK9FErg=w2400",-19.589025f,-65.753582f));
            turismo.add(new Turismo("TORRE DE LA COMPANIA DE JESUS","La mayor remodelación corresponde al s. XVIII, al rehacerse la fachada y la torre espadaña del Templo de la Compañía de Jesús. Esta obra se comenzó en 1701 y fue terminada en 1707. Sebastián de la Cruz, fue su autor como maestro cantero.","Calle Ayacucho","https://lh3.googleusercontent.com/e_98-rIzY26PmjLVx24cMCamaL0CuxvsoKNuhqAmXQyxqCrLNIMsBml6JcNs91BFimTJNGS6f7MB22qRSsjdot8eymCsKiHnqmS-sxg-7Ccz7PFV_vVLJLLmk9L-3lsZ6_VlEoS8JA=w2400",-19.588732f,-65.754800f));
            turismo.add(new Turismo("IGLESIA DE SAN FRANCISCO DE PADUA","En el templo se puede observar la imagen del Cristo de la Vera Cruz, que data del año 1550 por lo que es la más antigua de Bolivia, hermosa talla del crucificado, de aspecto indígena. El convento en su interior cuenta con una exposición de cuadros de la colonia, entre los cuales destaca uno del pintor colonial Melchor Pérez de Holguín, considerado entre los tres más grandes de América. Actualmente posee un museo sacro y un mirador que le permite al visitante observar el paisaje colonial de la ciudad.","Calle Tarija, esq. Nogales.","https://lh3.googleusercontent.com/kzSeo6qnyH1bB4rE9-Bi8ZH8jzg0locpZZFEtJje9BwAS4T9Llu-2he1wdrsMLPbGrocko3UlN22CGIzOL-1qTotGdOrfyusffNKRBAIpyC1i2KMBpcn3jA89U4MvFbU_3VXyDbD6Q=w2400",-19.591005f,-65.752855f));

            llenadortu = false;
        }
        return turismo;
    }
}
